hostname re
password zebra
enable password zebra

router ospf
 router-id 5.5.5.5

# LAN de RE (HE1)
 network 172.31.0.0/18 area 0


 # Enlace RE-RF
 network 192.168.100.16/30 area 0

 # Enlace RE-RL
 network 192.168.100.52/30 area 2

 # Enlace RE-RZY
 network 192.168.100.12/30 area 1

# Costos de interfaz
interface eth0
 ip ospf cost 43

interface eth1
 ip ospf cost 44

interface eth3
 ip ospf cost 42


