hostname rf
password zebra
enable password zebra

router ospf
 router-id 6.6.6.6
# LAN de RF (HF1)
 network 192.168.1.6/29 area 0
 # Enlace RF-RG
 network 192.168.100.20/30 area 0
# Enlace RF-RK
 network 192.168.100.48/30 area 0
 # Enlace RF-RE
 network 192.168.100.16/30 area 0
 # Enlace RF-RC
network 192.168.100.72/30 area 0
 
# Costos de interfaz
interface eth0
 ip ospf cost 50

interface eth1
 ip ospf cost 45

interface eth3
 ip ospf cost 52

interface eth4
 ip ospf cost 54
