hostname rzy
password zebra
enable password zebra

router ospf
 router-id 4.4.4.4
# LAN de RZY (HY1)
 network 10.10.8.0/21 area 1

# LAN de RZY (HZ1)
 network 10.10.10.0/30 area 1

# Enlaces RC (Área 1)
network 192.168.100.8/30 area 1

# Enlace hacia RE (Área 1)
network 192.168.100.12/30 area 1


# Costos
interface eth0
 ip ospf cost 39

interface eth1
 ip ospf cost 41


