hostname rj
password zebra
enable password zebra
router ospf
 router-id 10.10.10.10

# LAN de RJ (HJ1)
 network 10.2.0.0/19 area 2
# Enlace RJ-RWX
  network 192.168.100.36/30 area 2
# Enlace RJ-RK
  network 192.168.100.44/30 area 2
# Enlace RJ-RG
 network 192.168.100.40/30 area 0

#costo
interface eth0
 ip ospf cost 29

interface eth2
 ip ospf cost 32

interface eth3
 ip ospf cost 41


