hostname rl
password zebra
enable password zebra

router ospf
 router-id 12.12.12.12
# LAN de RL (HL1,HL2,HL3,HL4,HL5)
 network 192.168.0.0/24 area 2

 # Enlace RL-Rk
network 192.168.100.56/30 area 2
 # Enlace RL-RE
network 192.168.100.52/30 area 0
 
# Costos de interfaz
interface eth0
 ip ospf cost 33

interface eth3
 ip ospf cost 66


