# DHCP Server RL

default-lease-time 300;
max-lease-time 300;
authoritative;

subnet 192.168.0.0 netmask 255.255.240.0 {

  option routers 192.168.15.254;
  option broadcast-address 192.168.15.255;
  option domain-name "lan.local";
  option domain-name-servers 8.8.8.8, 1.1.1.1;

  range 192.168.0.100 192.168.0.200;
}

# Hosts con IP fija
host hl1 {
  hardware ethernet 02:00:00:00:00:01;
  fixed-address 192.168.0.1;
}

host hl2 {
  hardware ethernet 02:00:00:00:00:02;
  fixed-address 192.168.0.2;
}

