# DHCP Server RL
default-lease-time 300;
max-lease-time 300;
authoritative;

# Subred corregida /24
subnet 192.168.0.0 netmask 255.255.255.0 {

  option routers 192.168.0.254;
  option broadcast-address 192.168.0.255;
  option domain-name "empresa.izo";
  option domain-name-servers 192.168.10.1;

  # Rango dinámico de IPs
  range 192.168.0.3 192.168.0.100;
}

# Hosts con IP fija
host hl1 {
  hardware ethernet 02:00:00:00:00:01;
  fixed-address 192.168.0.1;
}

host hl2 {
  hardware ethernet 02:00:00:00:00:02;
  fixed-address 192.168.0.2;
}
