hostname rk
password zebra
enable password zebra

router ospf
 router-id 11.11.11.11
# LAN de RK (HK1)
 network 192.168.3.0/28 area 2

# Enlace RK-RJ
 network 192.168.100.44/30 area 2
# Enlace RK-RL
 network 192.168.100.56/30 area 2
# Enlace RK-RF
 network 192.168.100.48/30 area 0
 
#costos
interface eth0
 ip ospf cost 31

interface eth2
 ip ospf cost 34

interface eth3
 ip ospf cost 46


