hostname rwx
password zebra
enable password zebra
router ospf
 router-id 9.9.9.9

# LAN de RWX (HX1)
 network 192.168.2.0/29 area 2

# LAN de RWX (HW1)
 network 172.16.30.0/29 area 2

# Enlace RWX-RJ
 network 192.168.100.36/30 area 2
 # Enlace RWX-RH
 network 192.168.100.32/30 area 0


#costo
interface eth2
 ip ospf cost 30

interface eth3
 ip ospf cost 27


