hostname rg
password zebra
enable password zebra

router ospf
 router-id 7.7.7.7

# LAN de RG (HG1)
 network 10.1.1.0/29 area 0

 # Enlace RG-RH
 network 192.168.100.24/30 area 0

 # Enlace RG-RJ
 network 192.168.100.40/30 area 2

 # Enlace RG-RF
 network 192.168.100.20/30 area 0

 # Enlace RG-RB
 network 192.168.100.68/30 area 1

# Costos
interface eth0
 ip ospf cost 55

interface eth1
 ip ospf cost 60

interface eth3
 ip ospf cost 62

interface eth4
 ip ospf cost 64
